### ISSUE TITLE
Allow the user to change their preferred language

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-octane-vs-classic-cheat-sheet#63]
## Background

The app uses `ember-intl` to support multiple locales. Maintainers and contributors can experiment with translating the Octane cheatsheet in different languages so that we may reach out to more developers in the world.

## Problem

Now that we have 3 locales in place (`en-US`, `fr-FR`, and `pt-BR`), let's add a `<select>` element to allow the user to select their preferred language.

To keep the scope of the issue small, we will focus only on functionality (the ability to change the locale in app). Styling the `<select>` element, displaying user-friendly option labels, and persisting the locale across sessions are not a concern at this moment.

## TODOs

- [ ] Use Ember CLI to create a component called `<LocaleMenu>`. Copy-paste the following into the template:

   ```handlebars
    <select
      data-test-field="Locale"
      {{on "input" this.updateLocale}}
    >
      <option value="">
        {{t "component.locale-menu.select-your-preferred-language"}}
      </option>

      {{#each this.supportedLocales as |locale|}}
        <option value={{locale}}>
          {{locale}}
        </option>
      {{/each}}
    </select>
    ```

- [ ] Please complete the `<LocaleMenu>` component by:

    - Defining in the backing class:

        - `supportedLocales` (an array of strings `en-US`, `fr-FR`, and `pt-BR`)
        - `updateLocale` (an action)

    - Adding the translation value `Select your preferred language` in `translations/en-US.yaml`

    Note, you can update the locale by injecting the `intl` service and calling its `setLocale()` method:

    ```javascript
    // Example: Switch to pt-BR
    this.intl.setLocale('pt-BR');
    ```

- [ ] Call the `<InvokeMenu>` component from `app/templates/application.hbs`.

    ```handlebars
    <header>
      <img src="{{this.rootURL}}/assets/ember-octane_text-treatment.png" alt={{t "layout.application.logo-alt-text"}} class="header-logo">

      <LocaleMenu />
    </header>
    ```

- [ ] Write an application test in `tests/acceptance/homepage/en-us-test.js`. Check that, when we select a different locale, a translation is updated to that locale:

    - After we visit `/`, assert that a translation (pick one `data-test-field="Subsection Title"`) is in `en-US`.
    - Select `pt-BR`. (You can use the `fillIn` test helper to select an option.)
    - Assert that the translation is in `pt-BR`.
    - Select the default option `Select your preferred language`.
    - Assert that the translation is _still_ in `pt-BR`.
    - Select `fr-FR`.
    - Assert that the translation is in `fr-FR`.

- [ ] (optional) Write a rendering test in `integration/components/locale-menu-test.js`. Check that the `<select>` element has 3 options (4, counting the `Select your preferred language` option).

**Comment by ijlee2** [comment]
Hi, everyone. You can now help with this issue! 🎃

Please claim the issue by leaving a comment so that we can assign the issue to you. Thanks, and happy Hacktoberfest!

**Comment by talhaabbasi** [comment]
Hi, I would like to work on this. Can you please assign?

**Comment by sdahlbac** [comment]
I can have a go at this one

**Comment by ijlee2** [comment]
Thanks, @sdahlbac!
